GET http://127.0.0.1:8080/now
Accept: application/json

###

POST http://127.0.0.1:8080/plus
Content-Type: application/json

{
  "a": 10,
  "b": 5
}

###
POST http://127.0.0.1:8080/login
Content-Type: application/json
user: admin

{
  "username": "admin",
  "password": "123456"
}

###
GET http://127.0.0.1:8080/whoami
Accept: application/json

###
GET http://127.0.0.1:8080/showHeader
Accept: application/json
myHeader: test

###
