server:
  port: 8080

app:
  datasource:
    url: jdbc:postgresql://127.0.0.1:54326/ark
    username: postgres
    password: password
    max-active: 30
  auth:
    login: /login.html
    whitelist:
      - /login
      - /error
